add org.eclipse.emf.codegen.ecore to needed bundles
The GUI version of the SCL validator, released on 30 June 2026 (1.3.1-SNAPSHOT) fails to validate SCL files after the first click on Validate (nothing was displayed). It was OK if we click again on Validate, and the CLI version has no problem.
It appears that the NoClassDefFoundError for org.eclipse.emf.codegen.ecore was thrown during the first call to OCL validation, but not in the following calls.
So this bundle and its father is now added to the build.