Force com.google.guava version 30
package com.google.common.util.concurrent.internal is missing in com.google.guava version 31.1.0
Running the jar SCL validator failed with NoClassDefFoundError: com/google/common/util/concurrent/internal/InternalFutureFailureAccess